### ISSUE TITLE
进去播放没有声音，变成了话筒声音

### ISSUE THREAD

**Issue by hanwenbo** [Smeegol/MIDIPlayer#1]
进去播放没有声音，变成了话筒声音

**Comment by hanwenbo** [comment]
解决了  是因为我带耳机了  不带耳机用电脑自带的是可以听到的

**Comment by hanwenbo** [comment]
@Smeegol 终于回复啦  库主是转行了吗？我看github没提交记录了

**Comment by hanwenbo** [comment]
@Smeegol 可惜了一个好技术啊

**Comment by Smeegol** [comment]
@hanwenbo 但仍然奋战在 iOS 开发一线

**Comment by hanwenbo** [comment]
@Smeegol 😄 我还以为你转行了
